services:
  mitmproxy:
    image: mitmproxy/mitmproxy:latest
    container_name: CHANGEME-mitmproxy
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./mitmproxy-data:/home/mitmproxy/.mitmproxy
      - ./captures:/captures
    command: mitmweb --web-host 0.0.0.0 --set connection_strategy=lazy --ssl-insecure --set web_open_browser=false -w /captures/flows.mitm --set flow_detail=2
    restart: unless-stopped
